// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let first = 1,
  second = 1,
  next = 0,
  sum = 0;

while (next < 4000000) {  // next is less than 4 million
  next = first + second; 
  first = second;
  second = next;
  
  if (next % 2 === 0)
    sum += next;
}

console.log("The sum is:", sum)